/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Proyecto_Capacitacion.demo.VentasController;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ULISES
 */
public class CatalogoPartidasInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form PartidasInterfaz
     */
    public CatalogoPartidasInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Folio_Especifico = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_partidas = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        Cantidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Articulo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Folio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Busqueda_Global = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Precio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Estado = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        res_folio = new javax.swing.JLabel();

        jButton2.setText("Agregar");

        jButton3.setText("Modificar");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manejo de Ventas");

        jLabel2.setText("Folio:");

        jTextField1.setText("Ingresar folio....");

        jLabel3.setText("Total venta:");

        jTextField2.setText("Total...");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Articulo", "Cantidad", "Precio", "Importe", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Partidas:");

        jButton1.setText("Consultar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("Agregar");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 100, -1));

        jButton5.setText("Modificar");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Catálogo de Partidas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel6.setText("Folio:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        Folio_Especifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Folio_EspecificoActionPerformed(evt);
            }
        });
        getContentPane().add(Folio_Especifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 100, -1));

        jLabel7.setText("Total venta:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 268, -1, -1));

        jTextField4.setText("Total...");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 265, 100, -1));

        tabla_partidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Folio Venta", "Articulo", "Cantidad", "Precio", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_partidas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 296, 840, 356));

        jLabel8.setText("Partidas:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 268, -1, -1));

        jButton6.setText("Consultar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 100, -1));

        Cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadActionPerformed(evt);
            }
        });
        Cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CantidadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantidadKeyTyped(evt);
            }
        });
        getContentPane().add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 100, -1));

        jLabel9.setText("Cantidad:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 172, -1, -1));

        jLabel10.setText("Articulo:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 144, -1, -1));

        Articulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ArticuloKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ArticuloKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ArticuloKeyTyped(evt);
            }
        });
        getContentPane().add(Articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 100, -1));

        jLabel11.setText("Venta:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 110, -1, -1));

        Folio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FolioActionPerformed(evt);
            }
        });
        Folio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FolioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FolioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FolioKeyTyped(evt);
            }
        });
        getContentPane().add(Folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 100, -1));

        jLabel12.setText("Global:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 73, -1, -1));

        Busqueda_Global.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Busqueda_GlobalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Busqueda_GlobalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Busqueda_GlobalKeyTyped(evt);
            }
        });
        getContentPane().add(Busqueda_Global, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 100, -1));

        jLabel13.setText("Búsqueda:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel14.setText("Precio:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioActionPerformed(evt);
            }
        });
        Precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PrecioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PrecioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrecioKeyTyped(evt);
            }
        });
        getContentPane().add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 100, -1));

        jLabel15.setText("Estado:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoActionPerformed(evt);
            }
        });
        Estado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EstadoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EstadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EstadoKeyTyped(evt);
            }
        });
        getContentPane().add(Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 100, -1));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 100, -1));

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 100, -1));

        res_folio.setText(".");
        getContentPane().add(res_folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Folio_EspecificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Folio_EspecificoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Folio_EspecificoActionPerformed

    private void CantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadActionPerformed

    private void CantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadKeyPressed
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_CantidadKeyPressed

    private void CantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadKeyReleased
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_CantidadKeyReleased

    private void CantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadKeyTyped
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_CantidadKeyTyped

    private void ArticuloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ArticuloKeyPressed
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_ArticuloKeyPressed

    private void ArticuloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ArticuloKeyReleased
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_ArticuloKeyReleased

    private void ArticuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ArticuloKeyTyped
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_ArticuloKeyTyped

    private void FolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FolioActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_FolioActionPerformed

    private void FolioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FolioKeyPressed
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_FolioKeyPressed

    private void FolioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FolioKeyReleased
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_FolioKeyReleased

    private void FolioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FolioKeyTyped
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_FolioKeyTyped

    private void Busqueda_GlobalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Busqueda_GlobalKeyPressed
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_Busqueda_GlobalKeyPressed

    private void Busqueda_GlobalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Busqueda_GlobalKeyReleased
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_Busqueda_GlobalKeyReleased

    private void Busqueda_GlobalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Busqueda_GlobalKeyTyped
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_Busqueda_GlobalKeyTyped

    private void PrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioActionPerformed

    private void PrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecioKeyPressed
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_PrecioKeyPressed

    private void PrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecioKeyReleased
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_PrecioKeyReleased

    private void PrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecioKeyTyped
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_PrecioKeyTyped

    private void EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoActionPerformed

    private void EstadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EstadoKeyPressed
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_EstadoKeyPressed

    private void EstadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EstadoKeyReleased
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_EstadoKeyReleased

    private void EstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EstadoKeyTyped
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_EstadoKeyTyped

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        limpiarTabla();

        Busqueda_Global.setText("");
        Folio.setText("");
        Articulo.setText("");
        Cantidad.setText("");
        Precio.setText("");
        Estado.setText("");
        Folio_Especifico.setText("");
        busquedaTiempoReal();

    }//GEN-LAST:event_limpiarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //Cargar la tabla al ejecutar el programa
        busquedaTiempoReal();
    }//GEN-LAST:event_formWindowOpened

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        busquedaTiempoReal();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoPartidasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoPartidasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoPartidasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoPartidasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogoPartidasInterfaz().setVisible(true);
            }
        });
    }

    //Este método se utilizará para mostrar las ventas, la búsqueda se hace automáticamente en tiempo real
    public void busquedaTiempoReal() {

        limpiarTabla();

        DefaultTableModel tblModel = (DefaultTableModel) tabla_partidas.getModel();

        try {
            //UTILIZAR ENTIDADES
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/db_proyecto_capacitacion", "root", "1234");

            Statement st = con.createStatement();

            String v_global = Busqueda_Global.getText();
            String v_folio = Folio.getText();
            String v_articulo = Articulo.getText();
            String v_cantidad = Cantidad.getText();
            String v_precio = Precio.getText();
            String v_estado = Estado.getText();

            String v_folio_especifico = Folio_Especifico.getText();

            String sql = "";

            res_folio.setText("");

            //Usar Entity, no select, mismas sentencias SQL pero sin mandarlas así
            if (v_folio_especifico.isEmpty() == false) {
                //UTILIZAR ENTIDADES
                sql = "SELECT ventas.folio, partidas.articulo, partidas.cantidad, partidas.precio, partidas.estado FROM partidas "
                        + "INNER JOIN ventas "
                        + "ON partidas.id_venta = ventas.id "
                        + "WHERE "
                        + "ventas.folio = '" + v_folio_especifico + "' ORDER BY id_venta";

            } else if (v_global.isEmpty()) {
                System.out.println(v_global);
                System.out.println("Búsqueda específica");

                //UTILIZAR ENTIDADES
                sql = "SELECT ventas.folio, partidas.articulo, partidas.cantidad, partidas.precio, partidas.estado FROM partidas "
                        + "INNER JOIN ventas "
                        + "ON partidas.id_venta = ventas.id "
                        + "WHERE "
                        + "ventas.folio LIKE '%" + v_folio + "%' AND "
                        + "articulo LIKE '%" + v_articulo + "%' AND "
                        + "cantidad LIKE '%" + v_cantidad + "%' AND "
                        + "precio LIKE '%" + v_precio + "%' AND "
                        + "partidas.estado LIKE '%" + v_estado + "%' ORDER BY id_venta";

            } else {
                System.out.println(v_global);
                System.out.println("Búsqueda global");

                //UTILIZAR ENTIDADES
                sql = "SELECT ventas.folio, partidas.articulo, partidas.cantidad, partidas.precio, partidas.estado FROM partidas "
                        + "INNER JOIN ventas "
                        + "ON partidas.id_venta = ventas.id "
                        + "WHERE "
                        + "ventas.folio LIKE '%" + v_global + "%' OR "
                        + "articulo LIKE '%" + v_global + "%' OR "
                        + "cantidad LIKE '%" + v_global + "%' OR "
                        + "precio LIKE '%" + v_global + "%' OR "
                        + "partidas.estado LIKE '%" + v_global + "%' ORDER BY id_venta";

            }

            ResultSet rs = st.executeQuery(sql);

            if (rs.next() == false) {

                if (v_folio_especifico.isEmpty() == false) {
                    res_folio.setText("El folio: " + v_folio_especifico + " no existe");
                }

                System.out.println("///////////// No existe ese folio");
            } else {

                do {
//                    String id = String.valueOf(rs.getInt("id"));
                    String folio = rs.getString("folio");
                    String articulo = rs.getString("articulo");
                    String cantidad = rs.getString("cantidad");
                    String precio = rs.getString("precio");
                    String estado = rs.getString("estado");

                    System.out.println("salida - " + folio + " - " + articulo + " - " + cantidad + " - " + precio + " - " + estado);

                    String tbData[] = {folio, articulo, cantidad, precio, estado};
//                DefaultTableModel tblModel = (DefaultTableModel) tabla_ventas.getModel();

                    tblModel.addRow(tbData);
                } while (rs.next());
            }

            con.close();

        } catch (Exception e) {
            System.out.println("Error: " + e);
            System.out.println("||||||||||||||| Error a la hora de cargar la tabla de la db al programa");
        }

    }

    public void limpiarTabla() {
        DefaultTableModel tblModel = (DefaultTableModel) tabla_partidas.getModel();

        while (tblModel.getRowCount() > 0) {
            tblModel.removeRow(0);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Articulo;
    private javax.swing.JTextField Busqueda_Global;
    private javax.swing.JTextField Cantidad;
    private javax.swing.JTextField Estado;
    private javax.swing.JTextField Folio;
    private javax.swing.JTextField Folio_Especifico;
    private javax.swing.JTextField Precio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton limpiar;
    private javax.swing.JLabel res_folio;
    private javax.swing.JButton salir;
    private javax.swing.JTable tabla_partidas;
    // End of variables declaration//GEN-END:variables
}
