/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Proyecto_Capacitacion.demo.VentasController;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ULISES
 */
public class VentasInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form VentasInterfaz
     */
    public VentasInterfaz() {
        System.out.println("==================== Abrir interfaz ====================");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        folio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_ventas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        consultar = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        estado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        busqueda_global = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Folio_Especifico = new javax.swing.JTextField();
        res_folio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manejo de Ventas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 20, -1, -1));

        jLabel2.setText("Folio:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 131, -1, -1));

        folio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folioActionPerformed(evt);
            }
        });
        folio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                folioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                folioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                folioKeyTyped(evt);
            }
        });
        getContentPane().add(folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 128, 100, -1));

        tabla_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Folio", "Total", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabla_ventas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabla_ventasComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_ventas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 840, 356));

        jLabel4.setText("Ventas:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        getContentPane().add(consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 131, 100, -1));

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 100, -1));

        modificar.setText("Modificar");
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 100, -1));

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 100, -1));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 100, -1));

        jLabel3.setText("Búsqueda:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 59, -1, -1));

        jLabel5.setText("Total:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 162, -1, -1));

        jLabel6.setText("Estado:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 188, -1, -1));

        total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalKeyTyped(evt);
            }
        });
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 159, 100, -1));

        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });
        estado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                estadoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                estadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                estadoKeyTyped(evt);
            }
        });
        getContentPane().add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 185, 100, -1));

        jLabel7.setText("Global:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 100, -1, -1));

        busqueda_global.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busqueda_globalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                busqueda_globalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                busqueda_globalKeyTyped(evt);
            }
        });
        getContentPane().add(busqueda_global, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 97, 100, -1));

        jLabel8.setText("Folio:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 84, -1, -1));

        Folio_Especifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Folio_EspecificoActionPerformed(evt);
            }
        });
        getContentPane().add(Folio_Especifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 100, 100, -1));

        res_folio.setText(".");
        getContentPane().add(res_folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 103, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void folioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folioActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_folioActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        limpiarTabla();
        busqueda_global.setText("");
        folio.setText("");
        total.setText("");
        estado.setText("");
        Folio_Especifico.setText("");

        busquedaTiempoReal();
    }//GEN-LAST:event_limpiarActionPerformed

    public void limpiarTabla() {
        DefaultTableModel tblModel = (DefaultTableModel) tabla_ventas.getModel();

        while (tblModel.getRowCount() > 0) {
            tblModel.removeRow(0);
        }
    }

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_salirActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_consultarActionPerformed

    private void folioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_folioKeyPressed
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_folioKeyPressed

    private void folioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_folioKeyReleased
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_folioKeyReleased

    private void folioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_folioKeyTyped
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_folioKeyTyped

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoActionPerformed

    private void totalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyPressed
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_totalKeyPressed

    private void totalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyReleased
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_totalKeyReleased

    private void totalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyTyped
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_totalKeyTyped

    private void estadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estadoKeyPressed
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_estadoKeyPressed

    private void estadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estadoKeyReleased
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_estadoKeyReleased

    private void estadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estadoKeyTyped
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_estadoKeyTyped

    private void busqueda_globalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busqueda_globalKeyTyped
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_busqueda_globalKeyTyped

    private void busqueda_globalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busqueda_globalKeyPressed
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_busqueda_globalKeyPressed

    private void busqueda_globalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busqueda_globalKeyReleased
        // TODO add your handling code here:
        busquedaTiempoReal();
    }//GEN-LAST:event_busqueda_globalKeyReleased

    private void tabla_ventasComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabla_ventasComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_ventasComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //Cargar la tabla al ejecutar el programa
        busquedaTiempoReal();
    }//GEN-LAST:event_formWindowOpened

    private void Folio_EspecificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Folio_EspecificoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Folio_EspecificoActionPerformed

    //Este método se utilizará para mostrar las ventas, la búsqueda se hace automáticamente en tiempo real
    public void busquedaTiempoReal() {

        limpiarTabla();

        DefaultTableModel tblModel = (DefaultTableModel) tabla_ventas.getModel();

        try {
            //UTILIZAR ENTIDADES
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/db_proyecto_capacitacion", "root", "1234");

            Statement st = con.createStatement();

            String v_folio = folio.getText();
            String v_total = total.getText();
            String v_estado = estado.getText();
            String v_global = busqueda_global.getText();

            String v_folio_especifico = Folio_Especifico.getText();

            String sql = "";

            res_folio.setText("");

            //Usar Entity, no select, mismas sentencias SQL pero sin mandarlas así
            //UTILIZAR ENTIDADES
            if (v_folio_especifico.isEmpty() == false) {
                //UTILIZAR ENTIDADES
                System.out.println("folio a buscar - " + v_folio_especifico);
                sql = "SELECT * FROM ventas WHERE "
                        + "folio = '" + v_folio_especifico + "' ORDER BY id";

            } else if (v_global.isEmpty()) {
                System.out.println(v_global);
                //UTILIZAR ENTIDADES
                System.out.println("Búsqueda específica");
                sql = "SELECT * FROM ventas WHERE "
                        + "folio LIKE '%" + v_folio + "%' AND "
                        + "total LIKE '%" + v_total + "%' AND "
                        + "estado LIKE '%" + v_estado + "%' ORDER BY id";

            } else {
                System.out.println(v_global);
                //UTILIZAR ENTIDADES
                System.out.println("Búsqueda global");
                sql = "SELECT * FROM ventas WHERE "
                        + "folio LIKE '%" + v_global + "%' OR "
                        + "total LIKE '%" + v_global + "%' OR "
                        + "estado LIKE '%" + v_global + "%' ORDER BY id";
            }

            ResultSet rs = st.executeQuery(sql);

            if (rs.next() == false) {

                if (v_folio_especifico.isEmpty() == false) {
                    res_folio.setText("El folio: " + v_folio_especifico + " no existe");
                }

                System.out.println("No existe ese folio");
            } else {

                do {
                    //            String id = String.valueOf(rs.getInt("id"));
                    String folio = rs.getString("folio");
                    String total = rs.getString("total");
                    String estado = rs.getString("estado");

                    System.out.println("salida - " + folio + " - " + total + " - " + estado);

                    String tbData[] = {folio, total, estado};
//                DefaultTableModel tblModel = (DefaultTableModel) tabla_ventas.getModel();

                    tblModel.addRow(tbData);
                } while (rs.next());
            }

            con.close();

        } catch (Exception e) {
            System.out.println("Error: " + e);
            System.out.println("Error a la hora de cargar la tabla de la db al programa");
        }

    }

    /**
     * @param args the command line arguments
     */
    //Otro main, es necesario? el código se ejecuta igual sin el, investigar bien
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentasInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Folio_Especifico;
    private javax.swing.JButton agregar;
    private javax.swing.JTextField busqueda_global;
    private javax.swing.JButton consultar;
    private javax.swing.JTextField estado;
    private javax.swing.JTextField folio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton modificar;
    private javax.swing.JLabel res_folio;
    private javax.swing.JButton salir;
    private javax.swing.JTable tabla_ventas;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
